export enum Routes {
  HOME = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  TERMS = "/terms",
  BUSINESS = "/business",
  BADD = "/badd",
  ONBOARDING = "/onboarding",
  SURVEYS_OBJECTIVES = "/surveys-objectives",
  SURVEYS_MEMBERSHIP_SELECTION = "/surveys-membership-selection",
  SURVEYS_PAYMENTMETHOD_SELECTION = "/surveys-payment-method-selection",
  SURVEY_LIST = "/survey-list",
  CREATE_SURVEY = "/create-survey",
  SURVEY_CREATOR_WIDGET = "/survey-creator-widget",
  REGISTER_BUSINESS = "/register-business",
  UPLOAD_MEDIA = "/upload-media",
  PROFILE = "/profile",
  MARKETPLACE = "/marketplace",
  EDIT_SURVEY = "/edit-survey",
  CHANGE_PASSWORD = "/change-password",
  VERIFY = "/verify",
  TUTORIAL = "/tutorial",
  SETTINGS = "/settings",
  EARNINGS = "/earnings",
  MEMBERSHIP = "/membership",
}
